### ISSUE TITLE
在Keil MDK下，使用HSLink-Pro工程可能会出现卡顿的情况

### ISSUE THREAD

**Issue by naichajun** [cherry-embedded/CherryDAP#24]
在Keil MDK下，使用HSLink-Pro工程可能会出现卡顿，例如在点击`download`按钮或者打开Debugger的`Setting`界面的时候

**Comment by HalfSweet** [comment]
为了方便HSLink与上位机的交互，添加了一个HID的interface用于通信，可能会导致Keil MDK出现不影响使用的卡顿。

解决方案：在`CMakeLists.txt`中删掉`sdk_compile_definitions(-DCONFIG_USE_HID_CONFIG=1)`
