### ISSUE TITLE
硬件SPI下SWD协议有问题

### ISSUE THREAD

**Issue by jhembedded** [cherry-embedded/CherryDAP#8]
你好博主，我在HPM5301EVKLite板子上烧录了spi_over_swd.bin这个固件，使用KEIL对目标板(STM32F103C8)下载程序，发现不了板子，来回切换Debug和Trace栏，用示波器抓了一下发出来的波形，波形很差。可能会是哪里的原因？用hpm5301_daplink.bin这个固件没有这个问题，调试烧录都正常。

![image](https://github.com/cherry-embedded/CherryDAP/assets/30489909/6fc894d0-07ee-48c2-bf37-835c6984dc64)

![image](https://github.com/cherry-embedded/CherryDAP/assets/30489909/7e0d6e64-3e47-4025-b558-03d51ddb4566)

**Comment by RCSN** [comment]
对于下发的SWJ_CLOCK命令，比如keil
1、如果频率大于等于10M，则实际是80M。
2、如果频率大于等于1M并且小于10M，则实际是50M
3、如果频率小于1M，则实际是15M。

请确保示波器的采样率能否抓取50M波形。
STM32F103没试过，估计扛不住50M的SWD CLK。
